version: 1.2
workflows:
- name: VrsixConstruct
  subclass: WDL
  primaryDescriptorPath: /vrsix-construct.wdl
  readMePath: /README.md
  authors:
    - name: James Stevenson
      email: james.stevenson@nationwidechildrens.org
      affiliation: Nationwide Children's Hospital
      role: Bioinformatics Software Developer
    - name: Quinn Wai Wong
      email: wongq@ohsu.edu
      affiliation: Oregon Health & Science University
      role: Research Engineer