name: Checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stjude-rust-labs/sprocket-action@main
        with:
          lint: true
