name: Checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stjude-rust-labs/sprocket-action@main
        with:
          lint: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: gks-anvil/wdl-test@main
        with:
          wdl_file: vrsix-construct.wdl
          test_parameters: test/test_inputs.json
